name: wo-DISAMB
on:
  workflow_dispatch:
  issue_comment:
    types: [created]
jobs:
  call:
    cache-mode: write-only
    uses: mr-benty/zz-cachemode-delegation-0911/.github/workflows/callee_quiet.yml@main
